### ISSUE TITLE
Bug in magic shop in the town

### ISSUE THREAD

**Issue by mafranks** [mafranks/asciiRPG#23]
When I entered the magic shop I hit an error.

`-----------------
MAGIC SHOP:
Traceback (most recent call last):
  File "/Users/mafranks/PycharmProjects/asciiRPG/main.py", line 497, in <module>
    player = magic_shop(player)
  File "/Users/mafranks/PycharmProjects/asciiRPG/shops.py", line 132, in magic_shop
    player = magic_menu(player)
  File "/Users/mafranks/PycharmProjects/asciiRPG/shops.py", line 92, in magic_menu
    print(f"1. {spells['Fire']['Purchase']} Gold: Fire - Fire Attack")
KeyError: 'Fire'`

**Comment by mafranks** [comment]
Fixed in adc6e96892e20e636d0e28b753c91c685dac32e0
